# Generated by Django 3.1.6 on 2022-06-11 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210210_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='file',
        ),
    ]
